sudo: required
services:
  - docker
  
before_install:
  - docker build -t prabakaran/docker-react -f Dockerfile.dev .
script:
  - docker run prabakaran/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-213641575492"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
